// Starter list of DFW cities by county (a city can sit in more than one county).
// Owners add or turn off cities in Admin → DFW Coverage.
export const DFW_CITIES: { name: string; counties: string[] }[] = [
  { name: "Addison", counties: ["Dallas"] },
  { name: "Aledo", counties: ["Parker"] },
  { name: "Allen", counties: ["Collin"] },
  { name: "Alvarado", counties: ["Johnson"] },
  { name: "Alvord", counties: ["Wise"] },
  { name: "Anna", counties: ["Collin"] },
  { name: "Annetta", counties: ["Parker"] },
  { name: "Argyle", counties: ["Denton"] },
  { name: "Arlington", counties: ["Tarrant"] },
  { name: "Aubrey", counties: ["Denton"] },
  { name: "Azle", counties: ["Parker", "Tarrant"] },
  { name: "Balch Springs", counties: ["Dallas"] },
  { name: "Bedford", counties: ["Tarrant"] },
  { name: "Benbrook", counties: ["Tarrant"] },
  { name: "Blue Ridge", counties: ["Collin"] },
  { name: "Boyd", counties: ["Wise"] },
  { name: "Bridgeport", counties: ["Wise"] },
  { name: "Burleson", counties: ["Johnson", "Tarrant"] },
  { name: "Caddo Mills", counties: ["Hunt"] },
  { name: "Carrollton", counties: ["Dallas", "Denton"] },
  { name: "Cedar Hill", counties: ["Dallas"] },
  { name: "Celina", counties: ["Collin", "Denton"] },
  { name: "Chico", counties: ["Wise"] },
  { name: "Cleburne", counties: ["Johnson"] },
  { name: "Cockrell Hill", counties: ["Dallas"] },
  { name: "Colleyville", counties: ["Tarrant"] },
  { name: "Combine", counties: ["Kaufman"] },
  { name: "Commerce", counties: ["Hunt"] },
  { name: "Coppell", counties: ["Dallas", "Denton"] },
  { name: "Corinth", counties: ["Denton"] },
  { name: "Crandall", counties: ["Kaufman"] },
  { name: "Crowley", counties: ["Tarrant"] },
  { name: "Dallas", counties: ["Dallas"] },
  { name: "DeSoto", counties: ["Dallas"] },
  { name: "Decatur", counties: ["Wise"] },
  { name: "Denton", counties: ["Denton"] },
  { name: "Duncanville", counties: ["Dallas"] },
  { name: "Ennis", counties: ["Ellis"] },
  { name: "Euless", counties: ["Tarrant"] },
  { name: "Fairview", counties: ["Collin"] },
  { name: "Farmers Branch", counties: ["Dallas"] },
  { name: "Farmersville", counties: ["Collin"] },
  { name: "Fate", counties: ["Rockwall"] },
  { name: "Ferris", counties: ["Ellis"] },
  { name: "Flower Mound", counties: ["Denton"] },
  { name: "Forest Hill", counties: ["Tarrant"] },
  { name: "Forney", counties: ["Kaufman"] },
  { name: "Fort Worth", counties: ["Tarrant", "Wise"] },
  { name: "Frisco", counties: ["Collin", "Denton"] },
  { name: "Garland", counties: ["Dallas"] },
  { name: "Glenn Heights", counties: ["Dallas", "Ellis"] },
  { name: "Godley", counties: ["Johnson"] },
  { name: "Grand Prairie", counties: ["Dallas", "Ellis", "Tarrant"] },
  { name: "Grandview", counties: ["Johnson"] },
  { name: "Grapevine", counties: ["Tarrant"] },
  { name: "Greenville", counties: ["Hunt"] },
  { name: "Haltom City", counties: ["Tarrant"] },
  { name: "Haslet", counties: ["Tarrant"] },
  { name: "Heath", counties: ["Kaufman", "Rockwall"] },
  { name: "Hickory Creek", counties: ["Denton"] },
  { name: "Highland Park", counties: ["Dallas"] },
  { name: "Highland Village", counties: ["Denton"] },
  { name: "Hudson Oaks", counties: ["Parker"] },
  { name: "Hurst", counties: ["Tarrant"] },
  { name: "Hutchins", counties: ["Dallas"] },
  { name: "Irving", counties: ["Dallas"] },
  { name: "Italy", counties: ["Ellis"] },
  { name: "Josephine", counties: ["Collin"] },
  { name: "Joshua", counties: ["Johnson"] },
  { name: "Justin", counties: ["Denton"] },
  { name: "Kaufman", counties: ["Kaufman"] },
  { name: "Keene", counties: ["Johnson"] },
  { name: "Keller", counties: ["Tarrant"] },
  { name: "Kennedale", counties: ["Tarrant"] },
  { name: "Krum", counties: ["Denton"] },
  { name: "Lake Dallas", counties: ["Denton"] },
  { name: "Lake Worth", counties: ["Tarrant"] },
  { name: "Lancaster", counties: ["Dallas"] },
  { name: "Lavon", counties: ["Collin"] },
  { name: "Lewisville", counties: ["Denton"] },
  { name: "Little Elm", counties: ["Denton"] },
  { name: "Lucas", counties: ["Collin"] },
  { name: "Mabank", counties: ["Kaufman"] },
  { name: "Mansfield", counties: ["Ellis", "Johnson", "Tarrant"] },
  { name: "McKinney", counties: ["Collin"] },
  { name: "McLendon-Chisholm", counties: ["Rockwall"] },
  { name: "Melissa", counties: ["Collin"] },
  { name: "Mesquite", counties: ["Dallas", "Kaufman"] },
  { name: "Midlothian", counties: ["Ellis", "Johnson"] },
  { name: "Murphy", counties: ["Collin"] },
  { name: "Newark", counties: ["Wise"] },
  { name: "North Richland Hills", counties: ["Tarrant"] },
  { name: "Northlake", counties: ["Denton"] },
  { name: "Ovilla", counties: ["Ellis"] },
  { name: "Palmer", counties: ["Ellis"] },
  { name: "Parker", counties: ["Collin"] },
  { name: "Pilot Point", counties: ["Denton"] },
  { name: "Plano", counties: ["Collin", "Denton"] },
  { name: "Princeton", counties: ["Collin"] },
  { name: "Prosper", counties: ["Collin", "Denton"] },
  { name: "Quinlan", counties: ["Hunt"] },
  { name: "Red Oak", counties: ["Ellis"] },
  { name: "Rhome", counties: ["Wise"] },
  { name: "Richardson", counties: ["Collin", "Dallas"] },
  { name: "Richland Hills", counties: ["Tarrant"] },
  { name: "River Oaks", counties: ["Tarrant"] },
  { name: "Roanoke", counties: ["Denton"] },
  { name: "Rockwall", counties: ["Rockwall"] },
  { name: "Rowlett", counties: ["Dallas", "Rockwall"] },
  { name: "Royse City", counties: ["Hunt", "Rockwall"] },
  { name: "Sachse", counties: ["Collin", "Dallas"] },
  { name: "Saginaw", counties: ["Tarrant"] },
  { name: "Sanger", counties: ["Denton"] },
  { name: "Seagoville", counties: ["Dallas"] },
  { name: "Southlake", counties: ["Tarrant"] },
  { name: "Springtown", counties: ["Parker"] },
  { name: "Sunnyvale", counties: ["Dallas"] },
  { name: "Talty", counties: ["Kaufman"] },
  { name: "Terrell", counties: ["Kaufman"] },
  { name: "The Colony", counties: ["Denton"] },
  { name: "Trophy Club", counties: ["Denton"] },
  { name: "University Park", counties: ["Dallas"] },
  { name: "Venus", counties: ["Johnson"] },
  { name: "Watauga", counties: ["Tarrant"] },
  { name: "Waxahachie", counties: ["Ellis"] },
  { name: "Weatherford", counties: ["Parker"] },
  { name: "West Tawakoni", counties: ["Hunt"] },
  { name: "Westlake", counties: ["Tarrant"] },
  { name: "White Settlement", counties: ["Tarrant"] },
  { name: "Willow Park", counties: ["Parker"] },
  { name: "Wilmer", counties: ["Dallas"] },
  { name: "Wolfe City", counties: ["Hunt"] },
  { name: "Wylie", counties: ["Collin", "Rockwall"] },
];
