// All 254 Texas counties with the market each belongs to. Owners can move a county to another
// market in Admin → Coverage; this list only sets the starting market when a county is first added.
export const TEXAS_COUNTIES: { name: string; market: string }[] = [
  { name: "Anderson", market: "Other Texas" },
  { name: "Andrews", market: "Other Texas" },
  { name: "Angelina", market: "Other Texas" },
  { name: "Aransas", market: "Other Texas" },
  { name: "Archer", market: "Other Texas" },
  { name: "Armstrong", market: "Other Texas" },
  { name: "Atascosa", market: "San Antonio" },
  { name: "Austin", market: "Houston" },
  { name: "Bailey", market: "Other Texas" },
  { name: "Bandera", market: "San Antonio" },
  { name: "Bastrop", market: "Austin" },
  { name: "Baylor", market: "Other Texas" },
  { name: "Bee", market: "Other Texas" },
  { name: "Bell", market: "Other Texas" },
  { name: "Bexar", market: "San Antonio" },
  { name: "Blanco", market: "Other Texas" },
  { name: "Borden", market: "Other Texas" },
  { name: "Bosque", market: "Other Texas" },
  { name: "Bowie", market: "Other Texas" },
  { name: "Brazoria", market: "Houston" },
  { name: "Brazos", market: "Other Texas" },
  { name: "Brewster", market: "Other Texas" },
  { name: "Briscoe", market: "Other Texas" },
  { name: "Brooks", market: "Other Texas" },
  { name: "Brown", market: "Other Texas" },
  { name: "Burleson", market: "Other Texas" },
  { name: "Burnet", market: "Other Texas" },
  { name: "Caldwell", market: "Austin" },
  { name: "Calhoun", market: "Other Texas" },
  { name: "Callahan", market: "West Texas" },
  { name: "Cameron", market: "Other Texas" },
  { name: "Camp", market: "Other Texas" },
  { name: "Carson", market: "Other Texas" },
  { name: "Cass", market: "Other Texas" },
  { name: "Castro", market: "Other Texas" },
  { name: "Chambers", market: "Houston" },
  { name: "Cherokee", market: "Other Texas" },
  { name: "Childress", market: "Other Texas" },
  { name: "Clay", market: "Other Texas" },
  { name: "Cochran", market: "Other Texas" },
  { name: "Coke", market: "Other Texas" },
  { name: "Coleman", market: "Other Texas" },
  { name: "Collin", market: "DFW" },
  { name: "Collingsworth", market: "Other Texas" },
  { name: "Colorado", market: "Other Texas" },
  { name: "Comal", market: "San Antonio" },
  { name: "Comanche", market: "Other Texas" },
  { name: "Concho", market: "Other Texas" },
  { name: "Cooke", market: "Other Texas" },
  { name: "Coryell", market: "Other Texas" },
  { name: "Cottle", market: "Other Texas" },
  { name: "Crane", market: "Other Texas" },
  { name: "Crockett", market: "Other Texas" },
  { name: "Crosby", market: "Other Texas" },
  { name: "Culberson", market: "Other Texas" },
  { name: "Dallam", market: "Other Texas" },
  { name: "Dallas", market: "DFW" },
  { name: "Dawson", market: "Other Texas" },
  { name: "Deaf Smith", market: "Other Texas" },
  { name: "Delta", market: "Other Texas" },
  { name: "Denton", market: "DFW" },
  { name: "DeWitt", market: "Other Texas" },
  { name: "Dickens", market: "Other Texas" },
  { name: "Dimmit", market: "Other Texas" },
  { name: "Donley", market: "Other Texas" },
  { name: "Duval", market: "Other Texas" },
  { name: "Eastland", market: "Other Texas" },
  { name: "Ector", market: "West Texas" },
  { name: "Edwards", market: "Other Texas" },
  { name: "Ellis", market: "DFW" },
  { name: "El Paso", market: "El Paso" },
  { name: "Erath", market: "Other Texas" },
  { name: "Falls", market: "Waco" },
  { name: "Fannin", market: "Other Texas" },
  { name: "Fayette", market: "Other Texas" },
  { name: "Fisher", market: "Other Texas" },
  { name: "Floyd", market: "Other Texas" },
  { name: "Foard", market: "Other Texas" },
  { name: "Fort Bend", market: "Houston" },
  { name: "Franklin", market: "Other Texas" },
  { name: "Freestone", market: "Other Texas" },
  { name: "Frio", market: "Other Texas" },
  { name: "Gaines", market: "Other Texas" },
  { name: "Galveston", market: "Houston" },
  { name: "Garza", market: "Other Texas" },
  { name: "Gillespie", market: "Other Texas" },
  { name: "Glasscock", market: "Other Texas" },
  { name: "Goliad", market: "Other Texas" },
  { name: "Gonzales", market: "Other Texas" },
  { name: "Gray", market: "Other Texas" },
  { name: "Grayson", market: "Other Texas" },
  { name: "Gregg", market: "Other Texas" },
  { name: "Grimes", market: "Other Texas" },
  { name: "Guadalupe", market: "San Antonio" },
  { name: "Hale", market: "Other Texas" },
  { name: "Hall", market: "Other Texas" },
  { name: "Hamilton", market: "Other Texas" },
  { name: "Hansford", market: "Other Texas" },
  { name: "Hardeman", market: "Other Texas" },
  { name: "Hardin", market: "Other Texas" },
  { name: "Harris", market: "Houston" },
  { name: "Harrison", market: "Other Texas" },
  { name: "Hartley", market: "Other Texas" },
  { name: "Haskell", market: "Other Texas" },
  { name: "Hays", market: "Austin" },
  { name: "Hemphill", market: "Other Texas" },
  { name: "Henderson", market: "Other Texas" },
  { name: "Hidalgo", market: "Other Texas" },
  { name: "Hill", market: "Other Texas" },
  { name: "Hockley", market: "Other Texas" },
  { name: "Hood", market: "Other Texas" },
  { name: "Hopkins", market: "Other Texas" },
  { name: "Houston", market: "Other Texas" },
  { name: "Howard", market: "West Texas" },
  { name: "Hudspeth", market: "Other Texas" },
  { name: "Hunt", market: "DFW" },
  { name: "Hutchinson", market: "Other Texas" },
  { name: "Irion", market: "Other Texas" },
  { name: "Jack", market: "Other Texas" },
  { name: "Jackson", market: "Other Texas" },
  { name: "Jasper", market: "Other Texas" },
  { name: "Jeff Davis", market: "Other Texas" },
  { name: "Jefferson", market: "Other Texas" },
  { name: "Jim Hogg", market: "Other Texas" },
  { name: "Jim Wells", market: "Other Texas" },
  { name: "Johnson", market: "DFW" },
  { name: "Jones", market: "West Texas" },
  { name: "Karnes", market: "Other Texas" },
  { name: "Kaufman", market: "DFW" },
  { name: "Kendall", market: "San Antonio" },
  { name: "Kenedy", market: "Other Texas" },
  { name: "Kent", market: "Other Texas" },
  { name: "Kerr", market: "Other Texas" },
  { name: "Kimble", market: "Other Texas" },
  { name: "King", market: "Other Texas" },
  { name: "Kinney", market: "Other Texas" },
  { name: "Kleberg", market: "Other Texas" },
  { name: "Knox", market: "Other Texas" },
  { name: "Lamar", market: "Other Texas" },
  { name: "Lamb", market: "Other Texas" },
  { name: "Lampasas", market: "Other Texas" },
  { name: "La Salle", market: "Other Texas" },
  { name: "Lavaca", market: "Other Texas" },
  { name: "Lee", market: "Other Texas" },
  { name: "Leon", market: "Other Texas" },
  { name: "Liberty", market: "Houston" },
  { name: "Limestone", market: "Other Texas" },
  { name: "Lipscomb", market: "Other Texas" },
  { name: "Live Oak", market: "Other Texas" },
  { name: "Llano", market: "Other Texas" },
  { name: "Loving", market: "Other Texas" },
  { name: "Lubbock", market: "West Texas" },
  { name: "Lynn", market: "Other Texas" },
  { name: "McCulloch", market: "Other Texas" },
  { name: "McLennan", market: "Waco" },
  { name: "McMullen", market: "Other Texas" },
  { name: "Madison", market: "Other Texas" },
  { name: "Marion", market: "Other Texas" },
  { name: "Martin", market: "Other Texas" },
  { name: "Mason", market: "Other Texas" },
  { name: "Matagorda", market: "Other Texas" },
  { name: "Maverick", market: "Other Texas" },
  { name: "Medina", market: "San Antonio" },
  { name: "Menard", market: "Other Texas" },
  { name: "Midland", market: "West Texas" },
  { name: "Milam", market: "Other Texas" },
  { name: "Mills", market: "Other Texas" },
  { name: "Mitchell", market: "Other Texas" },
  { name: "Montague", market: "Other Texas" },
  { name: "Montgomery", market: "Houston" },
  { name: "Moore", market: "Other Texas" },
  { name: "Morris", market: "Other Texas" },
  { name: "Motley", market: "Other Texas" },
  { name: "Nacogdoches", market: "Other Texas" },
  { name: "Navarro", market: "Other Texas" },
  { name: "Newton", market: "Other Texas" },
  { name: "Nolan", market: "Other Texas" },
  { name: "Nueces", market: "Other Texas" },
  { name: "Ochiltree", market: "Other Texas" },
  { name: "Oldham", market: "Other Texas" },
  { name: "Orange", market: "Other Texas" },
  { name: "Palo Pinto", market: "Other Texas" },
  { name: "Panola", market: "Other Texas" },
  { name: "Parker", market: "DFW" },
  { name: "Parmer", market: "Other Texas" },
  { name: "Pecos", market: "Other Texas" },
  { name: "Polk", market: "Other Texas" },
  { name: "Potter", market: "Other Texas" },
  { name: "Presidio", market: "Other Texas" },
  { name: "Rains", market: "Other Texas" },
  { name: "Randall", market: "Other Texas" },
  { name: "Reagan", market: "Other Texas" },
  { name: "Real", market: "Other Texas" },
  { name: "Red River", market: "Other Texas" },
  { name: "Reeves", market: "Other Texas" },
  { name: "Refugio", market: "Other Texas" },
  { name: "Roberts", market: "Other Texas" },
  { name: "Robertson", market: "Other Texas" },
  { name: "Rockwall", market: "DFW" },
  { name: "Runnels", market: "Other Texas" },
  { name: "Rusk", market: "Other Texas" },
  { name: "Sabine", market: "Other Texas" },
  { name: "San Augustine", market: "Other Texas" },
  { name: "San Jacinto", market: "Other Texas" },
  { name: "San Patricio", market: "Other Texas" },
  { name: "San Saba", market: "Other Texas" },
  { name: "Schleicher", market: "Other Texas" },
  { name: "Scurry", market: "Other Texas" },
  { name: "Shackelford", market: "Other Texas" },
  { name: "Shelby", market: "Other Texas" },
  { name: "Sherman", market: "Other Texas" },
  { name: "Smith", market: "Other Texas" },
  { name: "Somervell", market: "Other Texas" },
  { name: "Starr", market: "Other Texas" },
  { name: "Stephens", market: "Other Texas" },
  { name: "Sterling", market: "Other Texas" },
  { name: "Stonewall", market: "Other Texas" },
  { name: "Sutton", market: "Other Texas" },
  { name: "Swisher", market: "Other Texas" },
  { name: "Tarrant", market: "DFW" },
  { name: "Taylor", market: "West Texas" },
  { name: "Terrell", market: "Other Texas" },
  { name: "Terry", market: "Other Texas" },
  { name: "Throckmorton", market: "Other Texas" },
  { name: "Titus", market: "Other Texas" },
  { name: "Tom Green", market: "West Texas" },
  { name: "Travis", market: "Austin" },
  { name: "Trinity", market: "Other Texas" },
  { name: "Tyler", market: "Other Texas" },
  { name: "Upshur", market: "Other Texas" },
  { name: "Upton", market: "Other Texas" },
  { name: "Uvalde", market: "Other Texas" },
  { name: "Val Verde", market: "Other Texas" },
  { name: "Van Zandt", market: "Other Texas" },
  { name: "Victoria", market: "Other Texas" },
  { name: "Walker", market: "Other Texas" },
  { name: "Waller", market: "Houston" },
  { name: "Ward", market: "Other Texas" },
  { name: "Washington", market: "Other Texas" },
  { name: "Webb", market: "Other Texas" },
  { name: "Wharton", market: "Other Texas" },
  { name: "Wheeler", market: "Other Texas" },
  { name: "Wichita", market: "Other Texas" },
  { name: "Wilbarger", market: "Other Texas" },
  { name: "Willacy", market: "Other Texas" },
  { name: "Williamson", market: "Austin" },
  { name: "Wilson", market: "San Antonio" },
  { name: "Winkler", market: "Other Texas" },
  { name: "Wise", market: "DFW" },
  { name: "Wood", market: "Other Texas" },
  { name: "Yoakum", market: "Other Texas" },
  { name: "Young", market: "Other Texas" },
  { name: "Zapata", market: "Other Texas" },
  { name: "Zavala", market: "Other Texas" },
];
